local CharacterKits = {
	Sans = {
		DisplayName = "Sans",
		Stats = {
			Health = 100,
			Stamina = 200,
			Mana = 1000,
			Attack = 1,
			Defense = 1,
		},
		AnimationIds = {
			Idle = 79524546702519,
			Walk = 76305972061747,
		},
		Block = {
			Name = "Bone Wall",
			DamageReduction = 0.9,
		},
		Passive = {
			Name = "Karmic Retribution",
			DotDamage = 2,
			DotTicks = 4,
			DotInterval = 0.5,
			OnHitManaLoss = 10,
		},
		Modes = {"Bones", "Telekinesis", "Blasters"},
		Abilities = {
			Bones = {
				Z = {
					Name = "Bone Volley",
					Cooldown = 2.5,
					Range = 18,
					Damage = 7,
					Knockback = 12,
					Stun = 0.25,
					ManaCost = 24,
				},
				X = {
					Name = "Crossbones Prison",
					Cooldown = 8,
					Range = 18,
					Damage = 14,
					Knockback = 8,
					Stun = 1.1,
					ManaCost = 60,
					IFrameTime = 0.9,
				},
				C = {
					Name = "Bone Wall Rush",
					Cooldown = 9,
					Range = 16,
					Damage = 16,
					Knockback = 28,
					Stun = 0.8,
					ManaCost = 70,
					BlueChance = 0.25,
				},
				V = {
					Name = "Bone Zone",
					Cooldown = 14,
					Range = 20,
					Damage = 18,
					Knockback = 20,
					Stun = 1,
					ManaCost = 100,
					Radius = 14,
				},
				G = {
					Name = "Retribution Counter",
					Cooldown = 18,
					Range = 20,
					Damage = 22,
					Knockback = 0,
					Stun = 2.2,
					ManaCost = 110,
					CounterWindow = 2,
				},
			},
			Telekinesis = {
				Z = {
					Name = "Telekinetic Grip",
					Cooldown = 6,
					Range = 18,
					Damage = 4,
					Knockback = 0,
					Stun = 1.2,
					ManaCost = 45,
					HoldDuration = 2.2,
				},
			},
			Blasters = {
				Z = {
					Name = "Manifest Blaster",
					Cooldown = 1.25,
					Range = 0,
					Damage = 0,
					Knockback = 0,
					Stun = 0,
					ManaCost = 40,
					MaxCount = 4,
				},
				X = {
					Name = "Tracked Blaster Burst",
					Cooldown = 4,
					Range = 22,
					Damage = 15,
					Knockback = 18,
					Stun = 0.55,
					ManaCost = 55,
					TrackCount = 2,
				},
			},
		},
	},
	Magnus = {
		DisplayName = "Magnus",
		Stats = {
			Health = 200,
			Stamina = 100,
			Mana = 0,
			Attack = 120,
			Defense = 200,
		},
		AnimationIds = {
			Idle = 0,
			Walk = 0,
		},
		Block = {
			Name = "Guard",
			DamageReduction = 0.65,
		},
		M1Damage = {9, 11, 15, 22},
		M1Knockback = {8, 10, 16, 28},
		Abilities = {
			Base = {
				Z = {
					Name = "Skewer Slam",
					Cooldown = 7,
					Range = 10,
					Damage = 28,
					Knockback = 0,
					Stun = 1.8,
					StaminaCost = 18,
				},
				X = {
					Name = "Piercing Lunge",
					Cooldown = 6,
					Range = 14,
					Damage = 24,
					Knockback = 30,
					Stun = 0.85,
					StaminaCost = 14,
				},
				C = {
					Name = "Black Dagger String",
					Cooldown = 8,
					Range = 9,
					Damage = 26,
					Knockback = 26,
					Stun = 0.95,
					StaminaCost = 16,
				},
				V = {
					Name = "Rising Gut Kick",
					Cooldown = 10,
					Range = 8,
					Damage = 30,
					Knockback = 40,
					Stun = 1.1,
					StaminaCost = 20,
				},
				G = {
					Name = "Black Sword Rain",
					Cooldown = 20,
					Range = 24,
					Damage = 11,
					Knockback = 14,
					Stun = 0.2,
					StaminaCost = 35,
					Windup = 2,
					Hits = 5,
				},
			},
		},
	},
}

return CharacterKits
